In [1]:
import numpy as np
import pandas as pd
tr_df =  np.loadtxt("cycle power plant train.csv",delimiter=",")
tr_df.shape[1]

5

In [2]:
def step_grad(points, learn_rate, M):
    N = points.shape[0]
    num_col = points.shape[1]
    
    new_M = np.zeros(num_col)
    
    for i in range(N):
        x = points[i, 0:num_col-1]
        x = np.append(x, 1)
        y = points[i, num_col-1]
        for j in range(num_col):
            new_M[j] += (-2/N) * (y - (M * x).sum()) * x[j]
        M = M - (learn_rate * new_M)
    
    return M

In [3]:
def gd(points, learn_rate, num_iter):
    num_col = points.shape[1]
    M = np.zeros(num_col)
    
    for i in range(num_iter):
        M = step_grad(points, learn_rate, M)        
    print(i, "Cost= ", cost(points, M))
    return M

In [4]:
def cost(points, M):
    total_cost = 0
    
    N = points.shape[0]
    num_col = points.shape[1]
    
    for i in range(N):
        x = points[i,0:num_col-1]
        x = np.append(x, 1)
        y = points[i,num_col-1]
        total_cost += (y - (M * x).sum()) ** 2
        
    total_cost = (1/N) * total_cost
    return total_cost

In [7]:
def run():
    learning_rate = 0.00001
    num_iterations = 1000
    m = gd(tr_df, learning_rate, num_iterations)
    return m[0:4], m[4]

In [8]:
m,c=run()
print(m,c)

999 Cost=  9800.052557305436
[-3.45628359 -3.89917151  0.42066753  4.07245427] 1.3627221431676957


In [9]:
test_data =np.loadtxt("cycle power plant test.csv", delimiter=",")

In [10]:
from sklearn.ensemble import GradientBoostingRegressor
x = tr_df[:, :-1]
y = tr_df[:, -1]
reg=GradientBoostingRegressor()
reg.fit(x,y)

GradientBoostingRegressor()

In [11]:
y_predict=reg.predict(test_data)
y_predict

array([470.56174391, 472.66297342, 435.27765416, ..., 438.71921598,
       452.8264231 , 445.09956345])

In [12]:
def predict(x, m, c):
    N = x.shape[0]
    y = np.zeros(N)
    
    for i in range(N):
        X = x[i,:]
        y[i] = (m * X).sum() + c
        
    return y
x_test = test_data

In [13]:
y_pred = predict(x_test, m, c)

In [14]:
y_pred

array([594.38619238, 569.0560762 , 360.63779622, ..., 457.69501728,
       445.80212114, 466.19727484])

In [15]:
y_predict.mean()


454.2197429449889

In [16]:
np.savetxt("cycle power plant predict.csv", y_predict, delimiter=',')